### ISSUE TITLE
500 server error generated when accessing https://grlc.knowledgepixels.com/api-git/knowledgepixels/bdj-nanopub-api/get-taxontaxon-nanopubs.csv via elton

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/knowledgepixels#1]
```
curl -I "https://grlc.knowledgepixels.com/api-git/knowledgepixels/bdj-nanopub-api/get-taxontaxon-nanopubs.csv"
```
yields
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 27 Sep 2023 15:54:02 GMT
Content-Type: text/csv; charset=UTF-8
Content-Length: 816
Connection: keep-alive
Link: <http://127.0.1.1,127.0.1.1:8088/api-git/knowledgepixels/bdj-nanopub-api/get-taxontaxon-nanopubs.csv?page=1>; rel=next, <http://127.0.1.1,127.0.1.1:8088/api-git/knowledgepixels/bdj-nanopub-api/get-taxontaxon-nanopubs.csv?page=1.0>; rel=last
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=;
X-Proxy-Cache: MISS
```

however, 

when indexing index via elton, a server error 500  is generated. 

```
elton interactions globalbioticinteractions/knowledgepixels
```

generated the following error - 

```
listing interactions [local]... -failed.
[31m[1mjava.lang.RuntimeException: listing interactions failed.[21m[39m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:97)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:204)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdInteractions.run(CmdInteractions.java:189)[23m[0m
[3m	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)[23m[0m
[3m	at picocli.CommandLine.access$1300(CommandLine.java:145)[23m[0m
[3m	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)[23m[0m
[3m	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)[23m[0m
[3m	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)[23m[0m
[3m	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)[23m[0m
[3m	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)[23m[0m
[3m	at picocli.CommandLine.execute(CommandLine.java:2078)[23m[0m
[3m	at org.globalbioticinteractions.elton.Elton.run(Elton.java:67)[23m[0m
[3m	at org.globalbioticinteractions.elton.Elton.main(Elton.java:58)[23m[0m
[31m[1mCaused by: org.globalbioticinteractions.dataset.DatasetRegistryException: failed to import datasets [local], please check the logs.[21m[39m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:93)[23m[0m
[3m	... 12 more[23m[0m
[31m[1mCaused by: org.eol.globi.data.StudyImporterException: problem importing from [file:///home/jorrit/proj/globi/data-new/knowledgepixels/./][21m[39m[0m
[3m	at org.eol.globi.data.DatasetImporterForMetaTable.importStudy(DatasetImporterForMetaTable.java:75)[23m[0m
[3m	at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleSingleNamespace(CmdUtil.java:106)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.lambda$handleNamespaces$1(CmdUtil.java:81)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:50)[23m[0m
[3m	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:75)[23m[0m
[3m	... 12 more[23m[0m
[31m[1mCaused by: org.apache.http.client.HttpResponseException: status code: 500, reason phrase: INTERNAL SERVER ERROR[21m[39m[0m
[3m	at org.eol.globi.util.ResourceServiceHTTP.getCachedRemoteInputStream(ResourceServiceHTTP.java:40)[23m[0m
[3m	at org.eol.globi.util.ResourceServiceHTTP.retrieve(ResourceServiceHTTP.java:28)[23m[0m
[3m	at org.eol.globi.util.ResourceServiceGzipAware.retrieve(ResourceServiceGzipAware.java:20)[23m[0m
[3m	at org.eol.globi.util.ResourceServiceLocalAndRemote.retrieve(ResourceServiceLocalAndRemote.java:26)[23m[0m
[3m	at org.globalbioticinteractions.elton.store.CachePullThroughPrestonStore.lambda$retrieve$0(CachePullThroughPrestonStore.java:59)[23m[0m
[3m	at bio.guoda.preston.store.DereferencerContentAddressed.get(DereferencerContentAddressed.java:21)[23m[0m
[3m	at org.globalbioticinteractions.elton.store.CachePullThroughPrestonStore.retrieve(CachePullThroughPrestonStore.java:64)[23m[0m
[3m	at org.globalbioticinteractions.cache.CacheProxy.retrieve(CacheProxy.java:33)[23m[0m
[3m	at org.globalbioticinteractions.cache.CacheProxyForDataset.retrieve(CacheProxyForDataset.java:55)[23m[0m
[3m	at org.globalbioticinteractions.dataset.DatasetWithCache.retrieve(DatasetWithCache.java:36)[23m[0m
[3m	at org.globalbioticinteractions.dataset.DatasetProxy.retrieve(DatasetProxy.java:27)[23m[0m
[3m	at org.globalbioticinteractions.dataset.DatasetProxy.retrieve(DatasetProxy.java:27)[23m[0m
[3m	at org.eol.globi.data.DatasetImporterForMetaTable$TableParserFactoryImpl.createParser(DatasetImporterForMetaTable.java:424)[23m[0m
[3m	at org.eol.globi.data.DatasetImporterForMetaTable.importTable(DatasetImporterForMetaTable.java:131)[23m[0m
[3m	at org.eol.globi.data.DatasetImporterForMetaTable.importStudy(DatasetImporterForMetaTable.java:70)[23m[0m
[3m	... 17 more[23m[0m
```

**Comment by jhpoelen** [comment]
fixed in most recent elton version.

```
elton pull globalbioticinteractions/knowledgepixels && elton interactions globalbioticinteractions/knowledgepixels | head -n2
```

yields

```
argumentTypeId	sourceOccurrenceId	sourceCatalogNumber	sourceCollectionCode	sourceCollectionId	sourceInstitutionCode	sourceTaxonId	sourceTaxonName	sourceTaxonRank	sourceTaxonPathIds	sourceTaxonPath	sourceTaxonPathNames	sourceBodyPartId	sourceBodyPartName	sourceLifeStageId	sourceLifeStageNamesourceSexId	sourceSexName	interactionTypeId	interactionTypeName	targetOccurrenceId	targetCatalogNumber	targetCollectionCode	targetCollectionId	targetInstitutionCode	targetTaxonId	targetTaxonName	targetTaxonRank	targetTaxonPathIds	targetTaxonPath	targetTaxonPathNames	targetBodyPartId	targetBodyPartName	targetLifeStageId	targetLifeStageName	targetSexId	targetSexName	basisOfRecordId	basisOfRecordName	http://rs.tdwg.org/dwc/terms/eventDate	decimalLatitude	decimalLongitude	localityId	localityNamereferenceDoi	referenceUrl	referenceCitation	namespace	citation	archiveURI	lastSeenAt	contentHash	eltonVersion
listing interactions [globalbioticinteractions/knowledgepixels]... https://en.wiktionary.org/wiki/support		https://www.checklistbank.org/dataset/9880/taxon/6FSV4									http://purl.obolibrary.org/obo/RO_0002470	eats						https://www.checklistbank.org/dataset/9880/taxon/77XPY											http://purl.org/np/RAlfH1ba32D9P9ODv0_pade_yQ8zmPmjPY6CxEXqyj_N8	Epilissus splendidus Fairmaire, 1889 (species) - trophically interacts with - Propithecus diadema Bennett, 1832 (species)	globalbioticinteractions/knowledgepixels	Species Interactions as published in nanopublications available through Biodiversity Data Journal and Knowledge Pixels.	https://github.com/globalbioticinteractions/knowledgepixels/archive/964c8a91f37d181b9b2ba19ddc72ae8bd301c28a.zip	2023-11-24T19:40:31.384Z	db290d7c6e14b7f7e240f1305ef44fe4ec769b69aaba2c6702084e7ce59d5ec6	0.12.12
```
